version: "2"
services: 
  deconz:
    image: deconzcommunity/deconz
    restart: always
    container_name: ${VIRTUAL_HOST}
    #privileged: true
    ports:
      - "127.0.0.1:43523:443"
      - "127.0.0.1:43524:80"
      - "127.0.0.1:6080:6080"
      - "127.0.0.1:5900:5900"
    volumes:
      - /opt/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      #- VIRTUAL_PROTO=https
      #- CERT_NAME=ca
      - TZ=Europe/Brussels
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DEBUG_HTTP=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_UID=1000
      - DECONZ_GID=1000
      - DECONZ_START_VERBOSE=0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
networks:
  default:
    external:
      name: reverse-proxy-network
